### ISSUE TITLE
Error using JavaScript code uploading files

### ISSUE THREAD

**Issue by lloydcarroll** [nftstorage/nft.storage#1651]
Ok, new issue. So, i'm using the https://nft.storage/docs/client/js/ javascript code to upload files. So, I was able to upload 10k png files using the upload Folder code looping through the files and storing them as an array. This works fine for each file being 1-3 MB each, totalling around 14.7GB each upload. Perfect. Now, I have to have ALL of the JSON files in ONE CID for the reveal. There's 100k images so there's 100k json files. The json files are around 1kb each. Total size of all 100k json is about 110MB. Baby bottle size in comparison. However, I get the following error when it runs through them. Let me clarify, it loops successfully through all the files and storing them. It then tries to upload them for a while (No where near the 3+ hours for images). It gets to the very end and then I get the following.

`Error: 524: 
    at pRetry.retries (file:///C:/Users/Tech/Downloads/nft-storage-quickstart/node_modules/nft.storage/src/lib.js:159:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RetryOperation._fn (C:\Users\Tech\Downloads\nft-storage-quickstart\node_modules\p-retry\index.js:50:12) {
  attemptNumber: 5,
  retriesLeft: 1
}`

Now, when I access the files, I seem to be able to access most of the I've tried. Can't possible try them all, so I try a few randoms, then I try the first and the last. They ALL seem to be there except for the last one, #100,000. Why is that? What is the issue? Why the last one. Now this last time I tried, NONE of them showed up.

**Comment by lloydcarroll** [comment]
Several times I run the script and NOTHING shows up.

**Comment by lloydcarroll** [comment]
Ok, now the CID is showing up with the files, but still they are not all getting there and I'm getting gateway error trying to access. During upload I got this

Error: 524: Origin Time-out
    at pRetry.retries (file:///C:/Users/Tech/Downloads/nft-storage-quickstart/node_modules/nft.storage/src/lib.js:159:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async RetryOperation._fn (C:\Users\Tech\Downloads\nft-storage-quickstart\node_modules\p-retry\index.js:50:12) {
  attemptNumber: 6,
  retriesLeft: 0
}

**Comment by dchoi27** [comment]
Sorry for the delay here - if you can make your metadata directory available we can try to reproduce!

**Comment by vasco-santos** [comment]
Hey @lloydcarroll 

Could you also show us the code you are using to create the upload? It looks like parts of your upload were consistently failing to upload with a timeout error from our IPFS Cluster. We use pRetry to attempt 5 multiple times if sporadic errors happen, but this looks not related to that as you tried multiple times.

**Comment by M1lfsh4k3** [comment]
Did you resolve this issue? Im experiencing the same thing --> https://github.com/nftstorage/nft.storage/issues/1787

**Comment by lloydcarroll** [comment]
I'll share that.

This is the full code utilizing the JS version. I'm using the
StoreDirectory portion as you can see.

// Import the NFTStorage class and File constructor from the 'nft.storage'
package
import { NFTStorage, File } from 'nft.storage'

// The 'mime' npm package helps us set the correct file type on our File
objects
import mime from 'mime'

// The 'fs' builtin module on Node.js provides access to the file system
import fs from 'fs'

// The 'path' module provides helpers for manipulating filesystem paths
import path, { dirname } from 'path'

import { CarReader } from ***@***.***/car'
// Paste your NFT.Storage API key into the quotes:
const NFT_STORAGE_KEY = 'APIKEY HERE'

/**
  * Reads an image file from `imagePath` and stores an NFT with the given
name and description.
  * @param {string} imagePath the path to an image file
  * @param {string} name a name for the NFT
  * @param {string} description a text description for the NFT
  */
async function storeNFT(imagePath, name, description) {
    // load the file from disk
    const image = await fileFromPath(imagePath)

    // create a new NFTStorage client using our API key
    const nftstorage = new NFTStorage({ token: NFT_STORAGE_KEY })

    // call client.store, passing in the image & metadata
    return nftstorage.store({
        image,
        name,
        description,
    })
}

async function storeCar(imagePath) {
    // load the file from disk

    const image = await fileFromPath(imagePath)
    const carReader = await CarReader.fromIterable({image})

    // create a new NFTStorage client using our API key
    const nftstorage = new NFTStorage({ token: NFT_STORAGE_KEY })

    // call client.store,arassing in the image & metadata
    return cid = await nftstorage.storeCar()
}

async function storeDirectory(imageName, imageName2, dirName) {

    const startX = 60000
    const files = []
    const fPath = "C:\\Users\\Tech\\Downloads\\ipfs-car-main\\ipfs-car-main
\\CAR\\DONE\\"
    const nftstorage = new NFTStorage({ token: NFT_STORAGE_KEY })

    for(let x=1; x<10001; x++) {

        files[x-1] = await fileFromPath(fPath + (x + startX) + ".png")


        console.log(files[x-1].name)
    }

    console.log(Date.now())

    return cid = await nftstorage.storeDirectory(files)
}

/**
  * A helper to read a file from a location on disk and return a File
object.
  * Note that this reads the entire file into memory and should not be used
for
  * very large files.
  * @param {string} filePath the path to a file to store
  * @returns {File} a File object containing the file content
  */
async function fileFromPath(filePath) {
    const content = await fs.promises.readFile(filePath)
    const type = mime.getType(filePath)
    //console.log("path.basename(filepath) = " + path.basename(filePath))
    return new File([content], path.basename(filePath), { type })
}


/**
 * The main entry point for the script that checks the command line
arguments and
 * calls storeNFT.
 *
 * To simplify the example, we don't do any fancy command line parsing.
Just three
 * positional arguments for imagePath, name, and description
 */
async function main() {
    const args = process.argv.slice(2)
    if (args.length !== 3) {
        console.error(`usage: ${process.argv[0]} ${process.argv[1]}
<image-path> <name> <description>`)
        process.exit(1)
    }

    const [imagePath, name, description] = args
    //store NFT
    //const result = await storeNFT(imagePath, name, description)

    //store Car files
    //const result = await storeCar(imagePath)

    //Store Dir
    const result = await storeDirectory(imagePath, name, description)

    console.log(result)
}

// Don't forget to actually call the main function!
// We can't `await` things at the top level, so this adds
// a .catch() to grab any errors and print them to the console.
main()
  .catch(err => {
      console.error(err)
      process.exit(1)
  })
