### ISSUE TITLE
Rate Limiting via nft.storage-tools

### ISSUE THREAD

**Issue by taconugget** [nftstorage/nft.storage#1997]
I did a small test of 100 CIDs and was rate limited after only 30 to a failure. Here is the crash report:

```
node import.js  ipfs100.txt
           
🔌 Using endpoint: https://api.nft.storage/
  Errored
💖 Total sent: 31
📌 Sending: 69
🔁 Requests/sec: 1.0

✖ Error: pinning QmTmuZ7oyqDL8NEE4Zp4Mm8WnSjCJnJDvqv9pFF94novam: 429: Too Many Requests
Headers: alt-svc,h3=":443"; ma=86400, h3-29=":443"; ma=86400,cf-ray,71cdd8a118337bec-LAX,connection,close,content-length,113,content-type,application/json,date,Fri, 17 Jun 2022 18:28:39 GMT,expect-ct,max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct",retry-after,28,server,cloudflare,vary,Accept-Encoding
Body: {
  "ok": false,
  "error": {
    "code": "ERROR_RATE_LIMITED",
    "message": "You are being rate limited"
  }
}

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^
Error: pinning QmTmuZ7oyqDL8NEE4Zp4Mm8WnSjCJnJDvqv9pFF94novam: 429: Too Many Requests

Headers: alt-svc,h3=":443"; ma=86400, h3-29=":443"; ma=86400,cf-ray,71cdd8a118337bec-LAX,connection,close,content-length,113,content-type,application/json,date,Fri, 17 Jun 2022 18:28:39 GMT,expect-ct,max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct",retry-after,28,server,cloudflare,vary,Accept-Encoding

Body: {
  "ok": false,
  "error": {
    "code": "ERROR_RATE_LIMITED",
    "message": "You are being rate limited"
  }
}

    at retry.retries (file:///Users/brad/nft.storage-tools/import.js:120:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (/Users/brad/nft.storage-tools/node_modules/p-retry/index.js:50:12) {
  attemptNumber: 6,
  retriesLeft: 0
}

Node.js v18.0.0
```

**Comment by alanshaw** [comment]
Ah yes I think this tool hasn't been updated to respect new rate limits.

**Comment by alanshaw** [comment]
Ok, I've updated the dependencies - please try again now.

**Comment by hybla0** [comment]
@alanshaw seems the same thing i reported [here](https://github.com/nftstorage/nft.storage-tools/issues/8)
