### ISSUE TITLE
Intermittent error when calling storeDirectory

### ISSUE THREAD

**Issue by robyn3choi** [nftstorage/nft.storage#2523]
We are using nft.storage v7.1.1. When calling the `storeDirectory` method, it often fails (seems to be about half the time) with the following error:
```
TypeError: body.stream(...).pipe is not a function
    at writeToStream (/var/task/node_modules/node-fetch/lib/index.js:651:17)
    at /var/task/node_modules/node-fetch/lib/index.js:1675:3
    at new Promise (<anonymous>)
    at fetch (/var/task/node_modules/node-fetch/lib/index.js:1437:9)
    at pRetry.retries (file:///var/task/node_modules/nft.storage/src/lib.js:208:32)
    at async RetryOperation._fn (/var/task/node_modules/p-retry/index.js:50:12)
```

**Comment by robyn3choi** [comment]
we haven't seen this error in several days, but in the past we've had a couple weeks where we didn't see it, and then it would come back for another several days

**Comment by robyn3choi** [comment]
We just got this error again when calling `storeDirectory`. Here's the error stack. The `(from api route) undefined:` error name was generated by our app, so ignore that part:
```
stack: (from api route) undefined: body.stream(...).pipe is not a function
    at writeToStream (/var/task/node_modules/node-fetch/lib/index.js:651:17)
    at /var/task/node_modules/node-fetch/lib/index.js:1675:3
    at new Promise (<anonymous>)
    at fetch (/var/task/node_modules/node-fetch/lib/index.js:1437:9)
    at pRetry.retries (file:///var/task/node_modules/nft.storage/src/lib.js:208:32)
    at async RetryOperation._fn (/var/task/node_modules/p-retry/index.js:50:12)
},
```

And here is a nicer version of the stack trace displayed in Sentry:

![image](https://github.com/nftstorage/nft.storage/assets/9066587/1d49f0e2-d29c-47d0-b941-e02d4d169949)
![image](https://github.com/nftstorage/nft.storage/assets/9066587/b8ddd580-e85a-4cd8-8a94-d72b72b75182)

**Comment by robyn3choi** [comment]
We're using nft.storage v7.1.1, next v14.2.1, node 18.x, and our app is hosted on Vercel.
