### ISSUE TITLE
Can't run build on nextjs

### ISSUE THREAD

**Issue by jaynguyens** [nftstorage/nft.storage#538]
I got stuck on this error when run `yarn build` on my app, I have triage and it turn out the problem is with the `nft.storage`. 

```
➜ yarn build
yarn run v1.22.10
$ next build
info  - Loaded env from /Users/jaynguyens/Workspaces/mesh-mellow/.env
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types  
info  - Creating an optimized production build  
Failed to compile.

./node_modules/@ipld/car/esm/lib/decoder.js
Attempted import error: 'decode' is not exported from '@ipld/dag-cbor' (imported as 'decodeDagCbor').


> Build error occurred
Error: > Build failed because of webpack errors
    at /Users/jaynguyens/Workspaces/mesh-mellow/node_modules/next/dist/build/index.js:397:19
    at async Span.traceAsyncFn (/Users/jaynguyens/Workspaces/mesh-mellow/node_modules/next/dist/telemetry/trace/trace.js:60:20)
    at async Object.build [as default] (/Users/jaynguyens/Workspaces/mesh-mellow/node_modules/next/dist/build/index.js:77:25)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I ran on a new build with only bit of code below and run `yarn build`.  Tried delete node_module and yarn.lock but still not work. Can someone please try and take a look.

```ts
import { NFTStorage, File } from 'nft.storage'

const apiKey = process.env.NEXT_PUBLIC_STORAGE_APIKEY
const client = new NFTStorage({ token: apiKey as string })

export { client, File }
```

**Comment by sicktastic** [comment]
@jaynguyens I feel like this is a common issues for Next.js projects.  Look into https://github.com/ipfs-shipyard/nft.storage/issues/215.   I am not sure it is solved, but some people were able to manage it by downgrading nft.storage.

**Comment by scottbolasevich** [comment]
any fixes to this besides upgrading to nextjs 12

**Comment by elizabeth-griffiths** [comment]
We're closing this issue. If you still need help please open a new issue.
