### ISSUE TITLE
File won't upload directly or via CAR

### ISSUE THREAD

**Issue by btouellette** [nftstorage/nft.storage#758]
The file (and it's associated CAR) attached aren't able to upload: [bad_file.zip](https://github.com/nftstorage/nft.storage/files/7516974/bad_file.zip)

From https://nft.storage/new-file (with file or with CAR): `Error uploading: NetworkError when attempting to fetch resource`

Using the node.js library `storeBlob`: 
```
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Response.json (file:///D:/contract/node_modules/@web-std/fetch/src/body.js:163:15)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Function.storeBlob (file:///D:/contract/node_modules/nft.storage/src/lib.js:97:20)
```

It appears to be blocked by Cloudflare, response to request below (Cloudflare Ray ID: 6ac3c25999db39b4):
```
<!DOCTYPE html>
<!--[if lt IE 7]> 
<html class="no-js ie6 oldie" lang="en-US">
<![endif]-->
<!--[if IE 7]>    
<html class="no-js ie7 oldie" lang="en-US">
<![endif]-->
<!--[if IE 8]>    
<html class="no-js ie8 oldie" lang="en-US">
<![endif]-->
<!--[if gt IE 8]><!--> 
<html class="no-js" lang="en-US">
  <!--<![endif]-->
  <head>
    <title>Attention Required! | Cloudflare</title>
    <meta charset="UTF-8" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
    <meta name="robots" content="noindex, nofollow" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />
    <!--[if lt IE 9]>
    <link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" type="text/css" media="screen,projection" />
    <![endif]-->
    <style type="text/css">body{margin:0;padding:0}</style>
    <!--[if gte IE 10]><!-->
    <script>
      if (!navigator.cookieEnabled) {
        window.addEventListener('DOMContentLoaded', function () {
          var cookieEl = document.getElementById('cookie-alert');
          cookieEl.style.display = 'block';
        })
      }
    </script>
    <!--<![endif]-->
  </head>
  <body>
    <div id="cf-wrapper">
      <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
      <div id="cf-error-details" class="cf-error-details-wrapper">
        <div class="cf-wrapper cf-header cf-error-overview">
          <h1 data-translate="block_headline">Sorry, you have been blocked</h1>
          <h2 class="cf-subheadline"><span data-translate="unable_to_access">You are unable to access</span> nft.storage</h2>
        </div>
        <!-- /.header -->
        <div class="cf-section cf-highlight">
          <div class="cf-wrapper">
            <div class="cf-screenshot-container cf-screenshot-full">
              <span class="cf-no-screenshot error"></span>
            </div>
          </div>
        </div>
        <!-- /.captcha-container -->
        <div class="cf-section cf-wrapper">
          <div class="cf-columns two">
            <div class="cf-column">
              <h2 data-translate="blocked_why_headline">Why have I been blocked?</h2>
              <p data-translate="blocked_why_detail">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p>
            </div>
            <div class="cf-column">
              <h2 data-translate="blocked_resolve_headline">What can I do to resolve this?</h2>
              <p data-translate="blocked_resolve_detail">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.</p>
            </div>
          </div>
        </div>
        <!-- /.section -->
        <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
          <p class="text-13">
            <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">6ac3c25999db39b4</strong></span>
            <span class="cf-footer-separator sm:hidden">&bull;</span>
            <span class="cf-footer-item sm:block sm:mb-1"><span>Your IP</span>: 50.39.184.205</span>
            <span class="cf-footer-separator sm:hidden">&bull;</span>
            <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
          </p>
        </div>
        <!-- /.error-footer -->
      </div>
      <!-- /#cf-error-details -->
    </div>
    <!-- /#cf-wrapper -->
    <script type="text/javascript">
      window._cf_translation = {};
    </script>
  </body>
</html>
```

**Comment by dchoi27** [comment]
Oh that's so strange. This is just happening with this file? What is the file?

**Comment by btouellette** [comment]
Just a 512x512 png

**Comment by dchoi27** [comment]
Hm this is so weird. I can replicate the error when I upload via the Web UI, but it works fine when uploading directly through the HTTP API (https://bafybeifrrmljxugwjg6yk4j6yavhuuv5pexrcghguybwozhcvpbqsel3gm.ipfs.dweb.link/). Might be a Web UI thing - @Codigo-Fuentes mind taking a look?

**Comment by JeffLowe** [comment]
We'll look into this!

**Comment by btouellette** [comment]
I was able to upload this directly via the HTTP API with my bearer token so presumably that bypasses whatever Cloudflare layer was blocking this. I do see it associated with my account now so feel free to close this if it doesn't seem like it will affect anyone else.

**Comment by Codigo-Fuentes** [comment]
I reproduced the error as well uploading from web... converting the bad file to jpg and back to png i was able to upload new file without problems https://bafkreidewg7t752npyue5wbhuwq53dfcxpms3yp7vfr7jn4l5noulyf2eu.ipfs.dweb.link/ @dchoi27 are there relevant logs for that Ray Id we can inspect?

**Comment by dchoi27** [comment]
The HTTP request should be the same between the HTTP API and the web client, right @alanshaw ?

**Comment by JeffLowe** [comment]
Awaiting implementation of logging (Splunk) to better diagnose and resolve.

**Comment by JeffLowe** [comment]
Closing.  If it occurs again will be caught by splunk and ticketed for resolution
